#pragma once

enum class EObjectEntity
{
	EOBJECTENTITY_VOID = 0,
	EOBJECTENTITY_STATICCOLLISION = 1,
	EOBJECTENTITY_RIGIDBODY = 2,
	EOBJECTENTITY_PRESSURESOFTBODY = 8,
	EOBJECTENTITY_SHATTER = 16,
	EOBJECTENTITY_KINEMATIC_LINKED = 32,
	EOBJECTENTITY_BACKWARDSCOMPATIBLE = 2147483647
};
