#pragma once

enum class RENDER_PRIMITIVE_INSTANCE_FLAGS
{
	TF_OPAQUE_EMISSIVE = 1,
	TF_TRANS_EMISSIVE = 2,
	TF_TRANSADD_EMISSIVE = 4,
	TF_OPAQUE_LIT = 8,
	TF_TRANS_LIT = 16,
	TF_DECAL = 32,
	TF_REFRACTIVE = 64,
	TF_LM_SKIN = 128,
	TF_FORCE_EMISSIVE = 256,
	TF_DISABLE_SHADER_LOD = 512,
	TF_DISCARD = 1024,
	TF_TRANSALL = 6,
	TF_ALL = -1
};

inline RENDER_PRIMITIVE_INSTANCE_FLAGS operator&(RENDER_PRIMITIVE_INSTANCE_FLAGS lhs, RENDER_PRIMITIVE_INSTANCE_FLAGS rhs)
{
	return static_cast<RENDER_PRIMITIVE_INSTANCE_FLAGS>(static_cast<int>(lhs) & static_cast<int>(rhs));
}
